# include: package:pedantic/analysis_options.1.9.0.yaml

analyzer:
  exclude: [flutter/**]
#  strong-mode:
#    implicit-casts: false
#    implicit-dynamic: false
  errors:
    todo: error
    missing_return: error
    avoid_print: error
    annotate_overrides: error
    prefer_final_fields: error
    prefer_interpolation_to_compose_strings: error
    always_use_package_imports: error
    avoid_relative_lib_imports: error
    unused_local_variable: error
    unused_field: error
    unused_import: error
    duplicate_import: error
    curly_braces_in_flow_control_structures: error
    camel_case_types: error
    avoid_unnecessary_containers: error
    unnecessary_new: error

linter:
  rules:
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - always_require_non_null_named_parameters
    - always_use_package_imports
    - annotate_overrides
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_return_types_on_setters
    - avoid_shadowing_type_parameters
    - avoid_types_as_parameter_names
    - avoid_unnecessary_containers
    - camel_case_extensions
    - camel_case_types
    - curly_braces_in_flow_control_structures
    - empty_catches
    - empty_constructor_bodies
    - library_names
    - library_prefixes
#    - lines_longer_than_80_chars
    - no_duplicate_case_values
    - null_closures
#    - omit_local_variable_types
    - prefer_adjacent_string_concatenation
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_final_fields
    - prefer_for_elements_to_map_fromIterable
    - prefer_generic_function_type_aliases
    - prefer_if_null_operators
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - prefer_single_quotes
    - prefer_spread_collections
    - recursive_getters
    - slash_for_doc_comments
#    - sort_child_properties_last
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - type_init_formals
#    - unawaited_futures
    - unnecessary_const
    - unnecessary_new
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_this
    - unrelated_type_equality_checks
    - use_function_type_syntax_for_parameters
    - use_rethrow_when_possible
    - valid_regexps
